### PR TITLE
Ci deploy simplify

### PR DESCRIPTION
**Pull request by deanvollebregt**

### CODE REVIEW

**Comment by deanvollebregt** [comment]
The aws region variable had two different names AWS_REGION and AWS_DEFAULT_REGION, both environment variables. I've hard coded this in as 'ap-southeast-2', it removes the need for two environment variables and makes debugging the ci-deploy script easier.

**Comment by jmortlock** [comment]
The ECR-REGION is different because the quicktravel base image is not hosted in ap-southeast-2 rather its in  eu-central-1
(https://semaphoreci.com/quicktravel/quicktravel/environment_variables)

**Comment by deanvollebregt** [comment]
Could I please move the base-image to ap-southeast-2, can keep a backup in eu-central-1. The CI deploy script has pivoted to accommodate a lot of apps, trying to simplify it. End goal is 3 scripts. Build, Test, Deploy

**Comment by jmortlock** [comment]
I believe the reason why its in this region to start with is because building the normal QT image from the base image is very slow to pull the image from the ap-southeast-2 region in semaphore (pushing apparently was fine)

Either way I would strongly object to hardcoding config, and rather provide sensible defaults if no input is provided.

**Pull request closed without merging**
